name: biztidy_mobile_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.7+8

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  get_it: ^8.0.2
  get: ^4.6.6
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  shared_preferences: ^2.3.3
  equatable: ^2.0.5
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.2
  sizing: ^1.1.2
  go_router: ^14.6.0
  flutter_svg: ^2.0.14
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2
  animate_gradient: ^0.0.3
  fluttertoast: ^8.2.8
  email_otp: ^3.0.2
  pin_code_fields: ^8.0.1
  iconsax: ^0.0.8
  iconsax_plus: ^1.0.0
  cupertino_will_pop_scope: ^1.2.1
  entry: ^1.0.0
  quds_popup_menu: ^0.0.1+1
  omni_datetime_picker: ^2.0.5
  intl: ^0.19.0
  # flutter_paypal: ^0.2.1
  onesignal_flutter: ^5.2.8
  http: ^1.2.2
  cached_network_image: ^3.4.1
  cloudinary_public: ^0.21.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.9.0
  image_cropper: ^9.0.0
  place_picker_google: ^0.0.15
  google_maps_flutter: ^2.12.0
  geolocator: ^13.0.3
  ionicons: ^0.2.2
  geocoding: ^3.0.0
  flutter_paypal_payment: ^1.0.8
  flutter_paystack_max: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.1"

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/tidytech_logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: Audiowide
      fonts:
        - asset: fonts/Audiowide-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-VariableFont_wdth,wght.ttf
    - family: Alice
      fonts:
        - asset: fonts/Alice-Regular.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter-VariableFont_opsz,wght.ttf
